# Generated by Django 6.0 on 2025-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(max_length=255)),
                ('profissao', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
    ]
